apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: three-tier
  labels:
    app: mongodb
spec:
  clusterIP: None  # Headless service required for StatefulSet
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
