apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      # Ensure frontend runs only on frontend nodes
      nodeSelector:
        role: frontend
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 688372068524.dkr.ecr.ap-south-1.amazonaws.com/capstone/frontend-img:frontend-234b627
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://api-svc:3500/api/tasks"
          ports:
            - containerPort: 3000
