apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: three-tier
spec:
  selector:
    role: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
